base_url = "https://cigrainger.com"
theme = "terminimal"
compile_sass = true
build_search_index = false
generate_feed = true
minify_html = true
title = "Christopher Grainger's Blog"
description = "Technical blogging. Mostly Elixir and data science. Also Rust and Nix."

[markdown]
highlight_code = true
highlight_theme = "dracula"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
render_emoji = true

[extra]
accent_color = "pink"
logo_text = "Christopher Grainger"
author = "Christopher Grainger"

menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "github", url = "https://github.com/cigrainger", newtab = true},
    {name = "twitter", url = "https://twitter.com/cigrainger", newtab = true},
]

taxonomies = [
    {name = "tags"},
]
