base_url = "https://cigrainger.com"
theme = "terminimal"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
accent_color = "pink"
logo_text = "Christopher Grainger"
author = "Christopher Grainger"

menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "github", url = "https://github.com/cigrainger", newtab = true},
    {name = "twitter", url = "https://twitter.com/cigrainger", newtab = true},
]

taxonomies = [
    {name = "tags"},
]
